---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
pygmentsstyle: "friendly"
indexes:
  category: "categories"
baseurl: "https://lk4d4.darth.io/"
title: "Blog about programming, cats and related things"
...
